#!/usr/bin/env python3
"""Build esphome/irin_www.js: ESPHome's web_server v3 page script plus wifi_link.js.

ESPHome's `local: true` page is a fixed blob that ignores js_include, so to add the
WiFi Setup link the firmware serves the stock v3 script itself (js_include) with our
addition appended. The stock script is extracted from the installed ESPHome package,
so it matches that ESPHome version.

Re-run after upgrading ESPHome (the version that builds the firmware, e.g. the HA
add-on), then copy irin_www.js next to the device YAML:

    python3 esphome/www/build_www.py [path/to/esphome/package]
"""

import gzip
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
OUT = HERE.parent / "irin_www.js"


def find_package() -> Path:
    if len(sys.argv) > 1:
        return Path(sys.argv[1])
    import esphome  # noqa: PLC0415  (only when no path is given)

    return Path(esphome.__file__).parent


def main() -> None:
    pkg = find_package()
    header = (pkg / "components/web_server/server_index_v3.h").read_text()
    start = header.index("INDEX_GZ[] PROGMEM = {")
    body = header[start : header.index("};", start)]
    html = gzip.decompress(bytes(int(b, 16) for b in re.findall(r"0x([0-9a-fA-F]{2})", body))).decode()

    scripts = re.findall(r"<script type=module crossorigin>(.*?)</script>", html, re.S)
    if len(scripts) != 1 or not html.endswith("</script></head><body><esp-app></esp-app></body></html>"):
        sys.exit("v3 page layout changed; check server_index_v3.h before regenerating")

    version = (pkg / "const.py").read_text()
    version = re.search(r'__version__ = "([^"]+)"', version).group(1)
    link = (HERE / "wifi_link.js").read_text()
    OUT.write_text(
        f"// GENERATED by esphome/www/build_www.py from ESPHome {version} web_server v3\n"
        "// (github.com/esphome/esphome-webserver) + esphome/www/wifi_link.js. Do not edit.\n"
        f"{scripts[0]}\n{link}"
    )
    print(f"wrote {OUT} ({OUT.stat().st_size} bytes, ESPHome {version})")


if __name__ == "__main__":
    main()
